image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
stages:
  - build
  - test
  - deploy
  
cache:
  paths:
    - node_modules/
    # Enables git-lab CI caching. Both .cache and public must be cached, otherwise builds will fail.
    - .cache/
    - public/
    
build_dependencies:
  stage: build
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
  artifacts:
    paths:
      - public/
    
Test_and_Audit: 
    stage: test
    script:
        - npm audit fix
        
deploy prod:  
   image: python:latest  
   stage: deploy  
   script:    
      - pip install awscli    
      - aws s3 sync ./public s3://huehairlounge.com

